esphome:
  name: garagedoors
  platform: ESP8266
  board: nodemcuv2
  includes:
    - workspace/garagedoors/wiegand_device.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  
  ap:
    ssid: "garagedoors"
    password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:       

# Enable code to be sent to HA
custom_component:
- lambda: |-
    auto wiegand = new WiegandReader(D1, D2, "python_script.garagedoors");
    return {wiegand};

# Enable control of the LED 
status_led:
  pin: D4 # GPIO2

# Open/Close sensor on garage doors 
binary_sensor:
- platform: gpio
  pin:
    number: D5 # GPIO14
    mode: INPUT_PULLUP
    inverted: False
  name: "Garage Door Sensor - Left"
  device_class: garage_door
  filters:
    - delayed_on_off: 100ms
- platform: gpio
  pin:
    number: D6 # GPIO12
    mode: INPUT_PULLUP
    inverted: False
  name: "Garage Door Sensor - Right"
  device_class: garage_door
  filters:
    - delayed_on_off: 100ms 
- platform: gpio
  pin:
    number: RX # GPIO3
    mode: INPUT_PULLUP
    inverted: False
  name: "Garage Door Bell"
  device_class: sound
  filters:
    - delayed_on_off: 100ms 

# Enable closing/opening garage doors
switch:
- platform: gpio
  id: relay1
  pin:
    number: D7 # GPIO05
    inverted: true
  restore_mode: ALWAYS_OFF
- platform: template
  name: "Garage Door - Left"
  icon: "mdi:garage"
  turn_on_action:
  - switch.turn_on: relay1
  - delay: 1s
  - switch.turn_off: relay1
- platform: gpio
  id: relay2
  pin:
    number: D8 # GPIO04
    inverted: true
  restore_mode: ALWAYS_OFF
- platform: template
  name: "Garage Door - Right"
  icon: "mdi:garage"
  turn_on_action:
  - switch.turn_on: relay2
  - delay: 1s
  - switch.turn_off: relay2
- platform: restart
  name: 'Garage Doors Restart'

